### ISSUE TITLE
Keys for weights should be symbols, but in generated model.jl they're strings

### ISSUE THREAD

**Issue by philtomson** [FluxML/ONNX.jl#2]
I'm getting this:

```
julia> using Flux, ONNX
julia> model = include("model.jl")
ERROR: LoadError: KeyError: key "conv10_w_0" not found
```

Looking at weights, the type is Dict{Symbol, Any}:

> julia> weights
> Dict{Symbol,Any} with 52 entries:
>   Symbol("fire3/squeeze1x1_w_0") => Dict{Symbol,Any}(Pair{Symbol,Any}(:tag, "array…
>   Symbol("fire8/squeeze1x1_w_0") => Dict{Symbol,Any}(Pair{Symbol,Any}(:tag, "array…

Looking at the model.jl file:
```
begin
    eel = Chain(Dropout(0.5f0), Conv(relu, weights["conv10_w_0"], weights["conv10_b_0"], (1, 1), (0, 0)), ((crab,)->mean(crab, (1, 2))), softmax)
```

Note that the key being passed to weights is a String type, not a Symbol type which is leading to the error on include("model.jl") above.

**Comment by philtomson** [comment]
I tried changing the code for extract_weights (called by write_weights in my pull request) to:

```
function extract_weights(onnx_proto)
    f = onnx_proto.graph.initializer
    weights = Dict{String, Any}()
    for ele in f
        weights[String(ele.name)] = ONNX.get_array(ele)
    end
    return weights
end

```

But that broke the bson writing here:
```

function write_weights(model_fn, onnx_proto)
    weights = extract_weights(onnx_proto)
    if '/' in model_fn
        cd(parent(model_fn))
    end
    bson("weights.bson", weights)
    return weights
end
```

So I changed load_model to only call extract_weights instead of calling write_weights:
```
function load_model(model)
    onnx_proto = read_onnx(model)
    #weights    = write_weights(model, onnx_proto)
    weights    = extract_weights( onnx_proto)
    model_expr = write_julia_file(model, onnx_proto)
    return weights, model_expr
end
```

And after doing that, it works either by eval'ing the model_expr that comes out of load_model or by calling include("model.jl")

**Comment by philtomson** [comment]
sorry, this issue is on my changes. The current ONNX writes weights to BSON and then the user reads the file back in with load_weights - at that point keys for the weight dict are strings, not symbols.

**Comment by ayush1999** [comment]
Any top level object in BSON.jl is of type `Dict{Symbol, Any}`. Hence, while reading the weights the symbols need to be converted back to strings.

**Comment by philtomson** [comment]
I fixed it in my pull request.
