### ISSUE TITLE
Maxpool filter does not match Flux.jl

### ISSUE THREAD

**Issue by charut** [FluxML/ONNX.jl#20]
I tried importing the MNIST LeCunnNet and had this error at the maxpool filter

```
MethodError: no method matching maxpool(::Array{Float32,4}, ::Tuple{Int64,Int64}; pad=(0, 0), stride=(2, 2))  
Closest candidates are:  
  maxpool(::AbstractArray{xT,N}, !Matched::PoolDims; kwargs...) where {xT, N} at C:\Users\temp\.julia\packages\TimerOutputs\7zSea\src\TimerOutput.jl:198  
in top-level scope at base\none  
in  at model.jl:11
```

I'm using Flux v0.8.3 and ONNX v0.1.0

**Comment by ayush-1506** [comment]
Have you pulled the latest changes?

**Comment by charut** [comment]
I can't pull the latest changes with `Pkg`: there is an issue in the Project.toml file. It's missing the "name", "uuid" and "version" entries.

**Comment by charut** [comment]
Issue is resolved with the latest update. Thank you.

Please note that, `Project.toml` needs to be updated. I could only install it after forking and changing the file myself. Also, the other toml file does not contain `Statistics` as a dependency and it should.
