### ISSUE TITLE
KeyError: key :TreeEnsembleRegressor not found

### ISSUE THREAD

**Issue by bielim** [FluxML/ONNX.jl#38]
I trained a Random Forest Regression in Python's scikit-learn and saved it in ONNX format. When trying to load the model in Julia using ONNX.jl, I get a `KeyError: key :TreeEnsembleRegressor not found`. 

Presumably regression trees are not implemented in ONNX.jl - are there any plans to include them in the future?

**Comment by ayush-1506** [comment]
Having a key is subject to it's availability in Flux. ONNX.jl is just a fancy way of calling Flux layers/functions using these keys. Hence, the focus is on loading deep learning models (which is what Flux is built for). Statistical/non-deep models (such as random forest regression) aren't meant to be loaded using ONNX.jl.
