### ISSUE TITLE
what is ONNX.jl status now?

### ISSUE THREAD

**Issue by zsz00** [FluxML/ONNX.jl#60]
what is ONNX.jl status now? 

Is the refactored version available ?
Where is the new version of the documentation?

**Comment by ToucheSir** [comment]
1. Still under active development, but you can try non-trivial models now: https://github.com/FluxML/ONNX.jl/pull/59
2. The version on master is the refactored version
3. Not up yet, but most functions have docstrings and there's an up-to-date [examples directory](https://github.com/FluxML/ONNX.jl/tree/master/examples). PRs welcome for getting docs set up :wink:
