### ISSUE TITLE
Protobuf 1.0

### ISSUE THREAD

**Issue by Moelf** [FluxML/ONNX.jl#74]
I tried to look at it it seems `ProtoType` -> `AbstractDecoder` and then I don't know what's what, here's an issue tracking ideas... I'd be happy to try to make it work but right now ONNX doesn't pass test on 1.8

**Comment by dfdx** [comment]
I see 2 parts here:
1. Encoder/decoder API
2. Generated Julia definitions of ONNX data types

If the generated definitions haven't changed too much, we can try to simply update the API, e.g. replace `readproto(io, ModelProto())` with `decode(ProtoDecoder(io), ModelProto)`. If it doesnt work, the next step would be to re-generate definitions and repeat the previous step. The most dangerous scenario would happen if the generated Julia types have different layout (e.g. different field names), although given how ProtoBuf works it's unlikely to be the case.

I'll be able to look at it in ~1-2 weeks, but feel free to jump in if it blocks you.

**Comment by dfdx** [comment]
Old definitions didn't work out of the box, and generating the new ones is currently blocked by JuliaIO/ProtoBuf.jl#211 . I will try again once it's resolved.

**Comment by Drvi** [comment]
Hey folks! A fix for https://github.com/JuliaIO/ProtoBuf.jl/issues/211 was submitted to the General registry, so this should be resolved soon.

I'm afraid that migrating from old ProtoBuf won't work without some elbow grease, but hopefully, it should be worth it. There is a [section in the docs](https://juliaio.github.io/ProtoBuf.jl/dev/#Migrating-from-earlier-versions-of-ProtoBuf.jl) that summarizes key changes. Let me know if you have any questions!

**Comment by dfdx** [comment]
Thanks @Drvi! I'm glad to see how consistent and robust PB v1 is.

I'm currently refactoring the code in #74. Due to the change in semantics of some types (notably, introduction of `OneOf`) a few dispatch paths have been broken, so it may take some time to recover it. Stay tuned!

**Comment by dfdx** [comment]
Finally fixed in #75

**Comment by Moelf** [comment]
wow, fantastic work
