### ISSUE TITLE
`LoadError: AssertionError: Don't understand this multi-output result of the graph` when loading model

### ISSUE THREAD

**Issue by eloyfelix** [FluxML/ONNX.jl#81]
### Package Version

0.2.0

### Julia Version

1.7.1

### OS / Environment

MacOs

### Describe the bug

I'm trying to load this model https://github.com/chembl/chembl_multitask_model and getting `LoadError: AssertionError: Don't understand this multi-output result of the graph`

### Steps to Reproduce

```julia
using ONNX

path = "chembl_31_multitask.onnx"

# dummy input
dummy = rand(Float32, 1024, 1)

# load the model
mt_chembl = ONNX.load(path, dummy)
```

the model is available here: https://github.com/chembl/chembl_multitask_model/tree/main/trained_models/chembl_31_model

### Expected Results

model to load and hopefully outputting some predictions!

### Observed Results

Error

### Relevant log output

```
ERROR: LoadError: AssertionError: Don't understand this multi-output result of the graph
Stacktrace:
 [1] load(io::IOStream, args::Matrix{Float32}; backends::Vector{Symbol}, exec::Bool)
   @ ONNX ~/.julia/packages/ONNX/VJnjv/src/load.jl:285
 [2] #138
   @ ~/.julia/packages/ONNX/VJnjv/src/load.jl:294 [inlined]
 [3] open(f::ONNX.var"#138#139"{Vector{Symbol}, Bool, Tuple{Matrix{Float32}}}, args::String; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ Base ./io.jl:330
 [4] open
   @ ./io.jl:328 [inlined]
 [5] #load#137
   @ ~/.julia/packages/ONNX/VJnjv/src/load.jl:293 [inlined]
 [6] load(filename::String, args::Matrix{Float32})
   @ ONNX ~/.julia/packages/ONNX/VJnjv/src/load.jl:293
 [7] top-level scope
   @ ~/projects/onnx_julia/onnx_julia.jl:18
```

**Comment by dfdx** [comment]
Please, check out `fix/independent-multioutput` branch and see if it works for you (both - loading and further usage).

It's a pretty interesting graph. Most graphs have only 1 output. Some have 2 or 3 outputs as a result of multioutput node. But this graph contains 653 independent variables in the output! I'm not sure what this graph does, but I'm certainly impressed.

**Comment by eloyfelix** [comment]
Tried it and it works, many thanks! Are you planning to release a new version soon?

The model is a Multi task network I wrote a while ago. Blogpost explaning it a bit: http://chembl.blogspot.com/2019/05/multi-task-neural-network-on-chembl.html.

Code to test:

```julia
using ONNX
import RDKitMinimalLib: get_mol, get_morgan_fp
import Umlaut: play!
import JSON

path = "chembl_31_multitask.onnx"
targets = JSON.parsefile("targets_31.json")

# dummy input
dummy = rand(Float32, 1024, 1)

# load the model
mt_chembl = ONNX.load(path, dummy)

# test a molecule
mol = get_mol("CC(=O)Oc1ccccc1C(=O)O")
fp_details = Dict{String, Any}("nBits" => 1024, "radius" => 2)
mfp = get_morgan_fp(mol, fp_details)

# convert the bitstring to a 1024×1 Matrix{Float32}
stf32(x) = parse(Float32, x)
mfp = map(stf32, split(mfp, ""))
mfp = reshape(mfp, (length(mfp), 1))

# test a molecule
out = play!(mt_chembl, mfp)
out = collect(Iterators.flatten(out))

res = tuple.(targets, out)
res = sort(res, by=res->res[2], rev=true)
```

results:
```
653-element Vector{Tuple{String, Float32}}:
 ("CHEMBL4296", 0.9186169)
 ("CHEMBL4980", 0.90448534)
 ("CHEMBL1980", 0.8791402)
 ("CHEMBL240", 0.819559)
 ("CHEMBL3602", 0.8004181)

 ⋮
```

screenshot of the same model deployed in JS with same exact results :)
<img width="1298" alt="Screenshot 2022-10-31 at 23 17 08" src="https://user-images.githubusercontent.com/1122541/199127714-fbe06f09-944a-4f76-932c-4edd4e6823e9.png">

**Comment by dfdx** [comment]
Oh, sound cool! Help someone in drug discovery - achievement unlocked! :smile: 

To merge and release it I need to add proper tests, and it's a bit more of work. If it's not urgent, you can expect it to land by the end of the week.

**Comment by eloyfelix** [comment]
It is not urgent. Many thanks again for the fix!

**Comment by dfdx** [comment]
The change is now in `master`, but I'll be able to make a release only tomorrow when I get my phone and my two-step authentication back.

**Comment by dfdx** [comment]
Here's the [PR](https://github.com/JuliaRegistries/General/pull/71846) for registration, version 0.2.1 should be ready in ~1 hour.

**Comment by eloyfelix** [comment]
and now installed! :)
