### ISSUE TITLE
Question about TensorProto

### ISSUE THREAD

**Issue by ordicker** [FluxML/ONNX.jl#86]
### Motivation and description

hi, 

Is there a reason why TensorProto implemented like this:
```
struct TensorProto
    dims::Vector{Int64}
    data_type::Int32
    segment::Union{Nothing,var"TensorProto.Segment"}
    float_data::Vector{Float32}
    int32_data::Vector{Int32}
    string_data::Vector{Vector{UInt8}}
    int64_data::Vector{Int64}
    name::String
    doc_string::String
    raw_data::Vector{UInt8}
    external_data::Vector{StringStringEntryProto}
    data_location::var"TensorProto.DataLocation".T
    double_data::Vector{Float64}
    uint64_data::Vector{UInt64}
end
```

And not something like this: 
```
struct TensorProto{T}
    dims::Vector{Int64}
    data_type::Int32
    segment::Union{Nothing,var"TensorProto.Segment"}
    data::Vector{T} # <----replace all the specific fields 
    string_data::Vector{Vector{UInt8}} #not sure about this
    name::String
    doc_string::String
    raw_data::Vector{UInt8} #not sure about this
    external_data::Vector{StringStringEntryProto}
    data_location::var"TensorProto.DataLocation".T
end
```

**Comment by dfdx** [comment]
The whole file onnx3_pb.jl was automatically generated from the corresponding proto file. I don't know exactly why ONNX authors used this proto layout, but a few possible reasons are:

* you cannot represent `Vector{T}` or `Vector{Any}` in ProtoBuf as these are not concrete data types
* you can represent it, but this representation is less efficient from the space or performance viewpoint

It doesn't mean we can't have a more high-level interface though. Anyway, be cautions about order of dimensions in tensors, which is reversed during tensor <> Julia array conversion.

**Comment by ordicker** [comment]
Got it.

I asked that be because I have to impelment many functions like 
```
TensorProto(t::AbstractArray{<NEWTYPE>,N}, name ="") where N = TensorProto(
    dims=collect(reverse(size(t))),
    data_type=elem_type_code(<NEWTYPE>),
    <NEWTYPE_field>_data = reshape(t, :),
    name=name)
```
I'm not sure how to implement high-level interface without changing the struct (and we won't do it). 
Do you have something in mind?

**Comment by dfdx** [comment]
How about this?

```julia
for (T, field) in [(Int32, :int32_data), ...]   # add more types here
    @eval TensorProto(t::AbstractArray{$T,N}, name ="") where N = TensorProto(
          dims=collect(reverse(size(t))),
          data_type=elem_type_code($T),
          $(field) = reshape(t, :),
          name=name)
end
```
I'm afraid changing the layout of `TensorProto` isn't an option because in this case ProtoBuf.jl won't be able to correctly read/write the tensor data. Yet, we can create any number of wrappers and helper functions for data definitions.

**Comment by ordicker** [comment]
Looks great! Thanks.
