### ISSUE TITLE
Julia 1.9.0 compatibility 

### ISSUE THREAD

**Issue by ordicker** [FluxML/ONNX.jl#91]
Hi, 

I tried to run ONNX.jl `] test` on julia 1.9.0 and got this error: 
```julia
Gemm: Error During Test at /home/dicker/workspace/ONNX.jl/test/saveload.jl:23
  Got exception outside of a @test
  MethodError: save_node!(::GraphProto{ValueInfoProto, ValueInfoProto, NodeProto, ValueInfoProto}, ::ONNX.OpConfig{:ONNX, typeof(Core.kwcall)}, ::Umlaut.Call{typeof(Core.kwcall)}) is ambiguous.
  
  Candidates:
    save_node!(g::GraphProto, ::ONNX.OpConfig{:ONNX, <:Union{typeof(Core.kwcall), typeof(ONNX.onnx_flatten)}}, op::Umlaut.Call)
      @ ONNX ~/workspace/ONNX.jl/src/save.jl:149
    save_node!(g::GraphProto, ::ONNX.OpConfig{:ONNX, <:Union{typeof(Core.kwcall), typeof(ONNX.maxpool)}}, op::Umlaut.Call)
      @ ONNX ~/workspace/ONNX.jl/src/save.jl:134
    save_node!(g::GraphProto, ::ONNX.OpConfig{:ONNX, <:Union{typeof(Core.kwcall), typeof(ONNX.conv)}}, op::Umlaut.Call)
      @ ONNX ~/workspace/ONNX.jl/src/save.jl:122
    save_node!(g::GraphProto, ::ONNX.OpConfig{:ONNX, <:Union{typeof(Core.kwcall), typeof(ONNX.onnx_gemm)}}, op::Umlaut.Call)
      @ ONNX ~/workspace/ONNX.jl/src/save.jl:109
    save_node!(g::GraphProto, ::ONNX.OpConfig{:ONNX, <:Union{typeof(Core.kwcall), typeof(ONNX.batch_norm)}}, op::Umlaut.Call)
      @ ONNX ~/workspace/ONNX.jl/src/save.jl:204
    save_node!(g::GraphProto, ::ONNX.OpConfig{:ONNX, <:Union{typeof(Core.kwcall), typeof(ONNX.onnx_gather)}}, op::Umlaut.Call)
      @ ONNX ~/workspace/ONNX.jl/src/save.jl:251
    save_node!(g::GraphProto, ::ONNX.OpConfig{:ONNX, <:Union{typeof(Core.kwcall), typeof(ONNX.onnx_unsqueeze)}}, op::Umlaut.Call)
      @ ONNX ~/workspace/ONNX.jl/src/save.jl:261
    save_node!(g::GraphProto, ::ONNX.OpConfig{:ONNX, <:Union{typeof(Core.kwcall), typeof(ONNX.onnx_split)}}, op::Umlaut.Call)
      @ ONNX ~/workspace/ONNX.jl/src/save.jl:272
    save_node!(g::GraphProto, ::ONNX.OpConfig{:ONNX, <:Union{typeof(Core.kwcall), typeof(ONNX.onnx_concat)}}, op::Umlaut.Call)
      @ ONNX ~/workspace/ONNX.jl/src/save.jl:289
```
I'm guessing that related to [this](https://github.com/FluxML/ONNX.jl/blob/d3deea56aa36a174a22cd544af98304602563c4d/src/save.jl#L44). 
I'm not sure how to approach it, can I have some help?

**Comment by dfdx** [comment]
It looks like `Core.kwfunc()` has been replaced with `Core.kwcall()`, possibly with different semantics. I will try to take a look at it later today.

**Comment by dfdx** [comment]
A quick note. The whole machinery around functions with keyword arguments has changed in Julia 1.9. It will take some time to understand how to bypass the change and what other parts of the package it may affect.

**Comment by ToucheSir** [comment]
I think `kwfunc` just returns `kwcall` now? So that still works as long as you don't rely on distinct kwsorters being returned for different functions.

**Comment by dfdx** [comment]
> as long as you don't rely on distinct kwsorters being returned for different functions.

...which is pretty much what we do :smile: 

To be more precise, we dispatch calls between methods of `save_node!()` based on function type encoded into `OpConfig`. For simple functions we use: 

```julia
OpConfig{backend, typeof(f)}
# e.g. 
OpConfig{:ONNX, typeof(*)}
```

For functions with keyword arguments we extend the config with the kw-based version of the function, e.g. 

```julia
OpConfig{backend, Union{typeof(f), typeof(kwfunc(f))}}
# e.g. 
OpConfig{:ONNX, Union{typeof(conv), typeof(var"#conv##kw")}}
```
This way a single function `save_node!(g::GraphProto, ::@opconfig_kw(:ONNX, conv), op::Umlaut.Call)` can catch call to `conv` with and without kw arguments. 

-------

In Julia 1.9, however, `kwfunc(f)` returns not a unique function like `var"#conv##kw"`, but instead a completely generic `kwcall`, on which we cannot dispatch. In #92 I try to mitigate it by always dispatching on the "main" function, e.g. `conv`, not `var"#conv##kw"`, but there seems to be more errors on the way.

**Comment by dfdx** [comment]
Ok, the remaining errors were actually easy to fix. Now it works both - in Julia 1.8 and Julia 1.9. The code is quite ugly though, so I will leave the PR open for a day to collect ideas on how to handle multiple Julia versions better.
