### ISSUE TITLE
UndefVarError: `args` not defined

### ISSUE THREAD

**Issue by ericphanson** [FluxML/ONNX.jl#97]
https://github.com/FluxML/ONNX.jl/blob/fb7e66d2090ba2a247e9daaa03ac3ca896cff53c/src/load.jl#L229

looks like this should be `inputs` instead of `args` (also looks like some test coverage is missing)

found here: https://discourse.julialang.org/t/loading-pytorch-faster-rcnn-with-onnx-fails/105201

**Comment by dfdx** [comment]
Fixed and will be published soon. Thanks for reporting!
